### ISSUE TITLE
It doesn´t show any output, and according the log apparently there is a loop

### ISSUE THREAD

**Issue by elBlacksmith** [camenduru/LaVie-colab#2]
Hi, 

Once I created the Gradio link and I selected the teddy bear example, it doesn´t show any output.
The time indicator keeps growing without stopping (I waited like 1000 seconds on a free Colab account , and the log shows what it looks a loop:

```
Running on public URL: https://xxxxxx.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
100% 50/50 [01:20<00:00,  1.60s/it]
torch.Size([16, 320, 512, 3])
100% 50/50 [01:19<00:00,  1.58s/it]
torch.Size([16, 320, 512, 3])
100% 50/50 [01:19<00:00,  1.60s/it]
torch.Size([16, 320, 512, 3])
100% 50/50 [01:19<00:00,  1.59s/it]
```
and it keeps like that.

**Comment by camenduru** [comment]
thanks for the info ❤ please test with the new code

**Comment by elBlacksmith** [comment]
> thanks for the info ❤ please test with the new code

It works.

Thanks!
